-- PMS 초기 스키마 (2026-08-21 재구축) — Flyway가 스키마의 유일한 소유자다.
-- ddl-auto=none 이므로 엔티티가 스키마를 만들지 않는다. 변경은 이 파일 수정이
-- 아니라 새 V__*.sql 추가로만 한다(적용된 마이그레이션은 되돌릴 수 없다).
-- 단일 스키마(public) — 모듈별 스키마는 2026-08-21 결정으로 폐기했다.

-- person 모듈 ---------------------------------------------------------------

-- 조직 노드: 회사(root) → 부문 → 팀 → 임의 깊이 트리
create table org_units (
    id        bigint       not null primary key,
    parent_id bigint,                                  -- 회사(root)만 null
    name      varchar(200) not null,
    version   bigint       not null default 0
);

-- 직급: coeff = 보정 가동률 단가 가중치
create table grades (
    id      bigint           not null primary key,
    name    varchar(100)     not null,
    coeff   double precision not null,
    version bigint           not null default 0
);

-- 권한 그룹: 가시성 scope 4단 + 프로젝트 밖 기능 플래그 4종
create table permission_groups (
    id                  bigint       not null primary key,
    name                varchar(100) not null,
    visibility_scope    varchar(20)  not null,
    create_project      boolean      not null default false,
    manage_contracts    boolean      not null default false,
    manage_all_projects boolean      not null default false,
    manage_org          boolean      not null default false,
    system_fixed        boolean      not null default false,
    version             bigint       not null default 0
);

-- 사람: 모듈 간 연결은 id로만 하므로 물리 FK를 걸지 않는다
create table people (
    id             bigint           not null primary key,
    name           varchar(100)     not null,
    org_unit_id    bigint           not null,
    grade_id       bigint           not null,
    group_id       bigint           not null,
    capacity       double precision not null,
    billable       boolean          not null default true,
    system_account boolean          not null default false,
    active         boolean          not null default true,
    version        bigint           not null default 0
);

create index ix_people_org_unit on people (org_unit_id, active);

-- project 모듈 --------------------------------------------------------------

create table projects (
    id                bigint           not null generated by default as identity primary key,
    client            varchar(200)     not null,
    name              varchar(300)     not null,
    -- 중복 판정용 정규화 값 (AC A1-2: trim · 연속 공백 축약 · 영문 대소문자 무시)
    normalized_client varchar(200)     not null,
    normalized_name   varchar(300)     not null,
    solution          varchar(200),
    engagement        varchar(20)      not null,
    -- 대표 PM. role=PM 배정 1행과 항상 일치해야 한다(§4 불변식)
    manager_id        bigint           not null,
    -- 계약 관점 M/M — 배정 M/M(실투입 계획)과 다른 수치다
    contract_mm       double precision not null default 0,
    start_date        date,
    end_date          date,
    status            varchar(30)      not null,
    progress          integer          not null default 0,
    deleted           boolean          not null default false,
    version           bigint           not null default 0
);

create index ix_projects_name_key on projects (normalized_client, normalized_name);
create index ix_projects_deleted on projects (deleted);

create table project_assignments (
    id         bigint           not null generated by default as identity primary key,
    project_id bigint           not null,
    person_id  bigint           not null,
    role       varchar(20)      not null,
    start_date date,
    end_date   date,
    monthly_mm double precision not null default 0,
    status     varchar(20)      not null,
    version    bigint           not null default 0
);

create index ix_assignments_project on project_assignments (project_id, status);
create index ix_assignments_person on project_assignments (person_id, status);
