-- 감사 로그 (PRD-pms §4 common · EPIC G) — 2026-08-21 "기록만 먼저" 도입분.
-- append-only: 수정·삭제 경로를 만들지 않는다(G1-2). 매핑에서도 모든 컬럼이
-- updatable=false 다.
-- 저장은 이 테이블 하나뿐 — 통합 로그(G1-3)와 프로젝트별 이력(G2-2)은 같은 행의
-- 두 조회 뷰다(이중 기록 금지 — 2026-08-06 결정).
create table audit_logs (
    id           bigint      not null generated by default as identity primary key,
    entity_type  varchar(60) not null,
    entity_id    bigint      not null,
    -- 프로젝트 스코프 이벤트에만 채운다 — 배정·역할처럼 entity_id가 프로젝트가 아닌
    -- 행을 프로젝트별로 거르기 위한 참조 컬럼(G2-1). 조직·계정 변경은 null
    project_id   bigint,
    action       varchar(20) not null,
    actor_id     bigint      not null,
    -- WEB | MCP — 화면에서 바꿨는지 챗에서 바꿨는지 (AI 쓰기 경로의 최소 안전장치)
    source       varchar(10) not null,
    -- 변경 전·후 스냅샷(JSON) — 바뀐 필드만 담는다. CREATE는 before가 null
    before_state text,
    after_state  text,
    created_at   timestamp with time zone not null
);

-- 프로젝트별 이력은 최신순 조회다 (G2-2)
create index ix_audit_project on audit_logs (project_id, created_at desc);
create index ix_audit_entity on audit_logs (entity_type, entity_id, created_at desc);
