-- resource · notification 모듈 골격 (2026-08-22) — 스키마를 먼저 세운다.
--
-- 로직보다 스키마를 앞세우는 이유: 적용된 마이그레이션은 되돌리지 않는 규칙이라
-- 표의 모양이 곧 계약이고, 멱등·회수 같은 불변식은 애플리케이션이 아니라 여기
-- 제약으로 서야 잊혀도 지켜진다.

-- resource 모듈 -------------------------------------------------------------

-- 월별 가용 M/M: 그 달만 다른 경우의 예외 행이다.
-- 행이 없으면 people.capacity 기본값을 쓴다 — 44명 × 12개월을 미리 채우지 않는다.
-- 가동률 자체는 저장하지 않는다(매 조회 계산 — 2026-08-06 캐시 미도입 결정).
create table capacities (
    id               bigint           not null generated by default as identity primary key,
    person_id        bigint           not null,
    year_month_value varchar(7)       not null,   -- "YYYY-MM"
    available_mm     double precision not null,
    version          bigint           not null default 0,
    constraint uq_capacity_person_month unique (person_id, year_month_value)
);

-- notification 모듈 ---------------------------------------------------------

-- 수신자별 1행. 공유 행 + 읽음 표로 나누지 않는 이유는 회수(F3-3)와 개인 알림
-- 설정(F1-5)이 전부 수신자 단위이기 때문이다.
create table notifications (
    id           bigint       not null generated by default as identity primary key,
    recipient_id bigint       not null,
    type         varchar(40)  not null,
    -- 대상 종류·id — 알림에서 대상으로 이동하는 데 쓴다(문구 파싱 금지)
    ref_type     varchar(60),
    ref_id       bigint,
    message      varchar(500) not null,
    -- 멱등 키 (F1-2 중복 이벤트 · F2-2·F3-2 스케줄러 재실행)
    dedupe_key   varchar(200) not null,
    read_flag    boolean      not null default false,
    created_at   timestamp with time zone not null,
    constraint uq_notification_dedupe unique (recipient_id, dedupe_key)
);

-- 목록은 언제나 "내 것을 최신순으로"다 (F1-3)
create index ix_notification_recipient on notifications (recipient_id, created_at desc);
-- 회수는 대상 + 유형으로 미읽음을 걷는다 (F3-3)
create index ix_notification_ref on notifications (ref_type, ref_id, type);
