-- 유지보수 도메인 (EPIC D — 계약/사이트/이슈 3층, PRD-pms §4) · 2026-08-23 조회분.
--
-- 3층인 이유(2026-08-06 재설계): 유지보수 계약은 연 단위이고 계약:고객사가 1:N이다
-- (실측 — 가온아이 1계약 45사이트). 완료 프로젝트에서 1:1로 파생되는 모델로는
-- OEM 채널 계약처럼 원천 프로젝트가 없는 계약을 담을 수 없다.
--
-- 이번 마이그레이션은 조회(US-D4·D3-4)까지의 스키마다. 쓰기(D2·D3)·이관(D1)이
-- 들어와도 표의 모양은 그대로이고 제약만 쓰인다 — 마이그레이션은 되돌리지 않으므로
-- 불변식을 여기 두고 애플리케이션이 잊어도 지켜지게 한다.

-- 계약 --------------------------------------------------------------------
-- source_project_id: 이관 생성 시 프로젝트와 1:1, 직접 등록(US-D2)은 null.
--   시드 105건은 전부 null이다(시트 실데이터라 이관 이력이 없다).
create table maintenance_contracts (
    id                  bigint       not null generated by default as identity primary key,
    source_project_id   bigint,
    contractor          varchar(200) not null,
    name                varchar(300) not null,
    -- 예정 | 신규 | 유지 | 종료 — MCP search_maintenance의 status 필터와 같은 집합
    -- (2026-08-11 양측 합의). 시드의 '자동연장'·'갱신' 2건은 적재 시 '유지'로
    -- 흡수하고 원문은 note에 남긴다(2026-08-23 결정).
    status              varchar(20)  not null,
    -- 원본 시트 섹션: 2026 계약 | 신규 예정 | 미체결·종료. status에서 파생되지
    -- 않는다(교차 실측 — 2026 계약↔예정 3건·신규 예정↔유지 1건)
    sheet_section       varchar(30),
    contract_date       date,
    -- 시트의 비날짜 계약일("진행중"·"자동연장" 등)을 원문으로 보존 (부록 B)
    contract_date_note  varchar(200),
    start_date          date,
    end_date            date,
    amount              bigint,
    monthly_amount      bigint,
    -- 영업대표 — 모듈 간 연결은 id로만 (PRD-pms §0)
    sales_rep_id        bigint,
    -- 대분류(검색엔진|인프라)와 라이선스·제품 사양("검색엔진 3Copy+추천모듈").
    -- 계약 레벨인 이유: 다중 사이트 계약에서도 계약당 한 값이고, 라이선스 수량은
    -- 사이트 속성이 아니라 상거래 조건이다(2026-08-23 결정)
    category            varchar(60),
    target_infra        varchar(200),
    regular_check       varchar(300),
    note                text,
    version             bigint       not null default 0
);

-- 목록의 기본 정렬이 종료일 내림차순이다 (search_maintenance description과 동일)
create index ix_contract_end_date on maintenance_contracts (end_date desc);
create index ix_contract_status on maintenance_contracts (status);
-- 이관 계약을 프로젝트에서 되찾는 경로 (D4-2 원 프로젝트 링크)
create index ix_contract_source_project on maintenance_contracts (source_project_id);

-- 사이트 ------------------------------------------------------------------
-- 담당 엔지니어의 정본이 여기다(사이트 단위) — 이슈 기본 배정의 원천.
-- engineer_id는 nullable: 신규 예정·종료 섹션의 사이트는 미배정이고, "미배정
-- 이슈" 필터(D3-4)가 그 상태를 화면에서 보여 준다.
create table maintenance_sites (
    id          bigint       not null generated by default as identity primary key,
    contract_id bigint       not null references maintenance_contracts (id),
    name        varchar(200) not null,
    -- OEM | ENT — 없는 사이트가 다수라 nullable. OEM 채널은 원천 프로젝트가 없는
    -- 계약의 근거로 PRD가 이미 쓰는 구분이다(US-D2)
    channel     varchar(20),
    -- 서버 사양은 사이트 속성이다(2026-08-23 결정): 시드는 계약 행에 적혀 있지만
    -- 실제 값이 45개 사이트 중 한 곳을 가리킨다("태광그룹- 1번서버 …")
    server_spec varchar(300),
    -- 담당 엔지니어의 정본 (PRD-pms §4) — 이슈 기본 배정이 여기서 나온다
    engineer_id bigint,
    version     bigint       not null default 0
);

create index ix_site_contract on maintenance_sites (contract_id);
-- 사이트명은 keyword 검색의 유일한 도달 경로다 (D4-1 — 45사이트 계약에서
-- 사용자는 "가천대길병원"으로 부르고 그 문자열은 계약명·계약사에 없다)
create index ix_site_name on maintenance_sites (name);
create index ix_site_engineer on maintenance_sites (engineer_id);

-- 연락처 ------------------------------------------------------------------
-- 구 시트 "담당자 정보" 텍스트 블롭의 정규화. 원문 형식이 불규칙해서
-- (이름·직급·전화·이메일이 다 있는 것 / 전화만 / 회사명 접두) raw를 보존하고
-- 확실히 뽑히는 것만 컬럼에 담는다(2026-08-23 결정) — 파싱 실패가 정보 유실로
-- 이어지지 않게 한다.
create table maintenance_contacts (
    id      bigint       not null generated by default as identity primary key,
    site_id bigint       not null references maintenance_sites (id),
    -- 계약사 | 고객사
    party   varchar(20)  not null,
    name    varchar(100),
    title   varchar(60),
    phone   varchar(60),
    email   varchar(200),
    raw     varchar(400) not null,
    version bigint       not null default 0
);

create index ix_contact_site on maintenance_contacts (site_id);

-- 이슈 --------------------------------------------------------------------
-- 구 이슈 게시판의 대체. site_id는 nullable: 시드 이슈 14건 중 7건은 태그가
-- 유지보수 사이트가 아닌 프로젝트 고객사를 가리켜 계약에 연결되지 않는다
-- (부록 B "미연결 실데이터 그대로 둠"). 연결 기준은 계약명·계약사·사이트명
-- 3종 일치(2026-08-14 확정).
create table maintenance_issues (
    id           bigint       not null generated by default as identity primary key,
    site_id      bigint       references maintenance_sites (id),
    -- 장애 | 문의 | 요청
    type         varchar(20)  not null,
    title        varchar(300) not null,
    -- 접수 | 처리중 | 고객확인대기 | 완료
    status       varchar(20)  not null,
    -- 기본값은 사이트의 engineer_id이고, 재배정되면 여기서 갈라진다 (D3-1·D3-2)
    assignee_id  bigint,
    received_at  date         not null,
    completed_at date,
    version      bigint       not null default 0
);

-- "내 담당 열린 이슈"가 조회 한 번에 나와야 한다 (D3-4)
create index ix_issue_assignee_status on maintenance_issues (assignee_id, status);
create index ix_issue_site on maintenance_issues (site_id);

-- 코멘트 ------------------------------------------------------------------
-- append-only: 수정·삭제 경로를 만들지 않는다(D3-3 — 구 MaintenanceLog 불변식
-- 계승). 보정은 새 코멘트로만 한다.
-- 시드에는 코멘트 본문이 없고 개수만 있어 적재는 0건이다. 표와 조회 경로를
-- 지금 세우는 이유는 MCP list_maintenance_logs의 port 계약이 comments 배열을
-- 요구하기 때문이다(IssueView.comments — 2026-08-23 결정).
create table issue_comments (
    id         bigint                   not null generated by default as identity primary key,
    issue_id   bigint                   not null references maintenance_issues (id),
    author_id  bigint                   not null,
    content    text                     not null,
    created_at timestamp with time zone not null
);

create index ix_comment_issue on issue_comments (issue_id, created_at);
